name:                owenbot
version:             0.1.0.0
github:              "yellowtides/owenbot-hs"
author:              "Infowmatics Devs"
copyright:           "2020 Infowmatics Devs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A neat Discord bot written in Haskell.

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- cassava
- containers
- discord-haskell
- directory
- hashable
- hoogle
- http-conduit
- network-bsd
- parsec
- pointfree
- process
- random
- regex-tdfa
- split
- time
- text
- unix
- unliftio
- unordered-containers
- uri-encode
- vector

library:
  source-dirs:
    - src
    - src/receivers

executables:
  owenbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - owenbot

tests:
  owenbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    dependencies:
    - owenbot
    - QuickCheck
    - quickcheck-instances # required for arbitrary Text
    - hspec
